version: "1"
services:
  mongo:
    container_name: app-database
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"  
    networks:
      - app-network  
  backend:
    container_name: backend-api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    # Add any environment variables here if needed
    # environment:
    #   - VARIABLE_NAME=value
    depends_on:
      - mongo
    networks:
      - app-network  
    
  frontend:
    container_name: app-frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # Add any environment variables here if needed
    # environment:
    #   - VARIABLE_NAME=value
    depends_on:
      - backend
    stdin_open: true
    tty: true  
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  data: