const coderoute = require("./Routes/coderoutes");
const userRoutes = require("./Routes/userRoute");
const express = require("express");
const cors = require("cors");
const cookieParser = require("cookie-parser");
const bodyParser = require("body-parser");
const fileUpload = require("express-fileupload");

const errMiddleware = require("./middleware/error");
const app = express();
app.use(cookieParser());
app.use(cors());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(fileUpload());
console.log("this is app");
app.use("/api/v1", userRoutes);
app.use("/api/v1", coderoute);
app.use(errMiddleware);
module.exports = app;
